Add rate limit to Sign in
indico/indico pull request #5727
Opened 2023-04-06 09:49 UTC by openprojects

Add rate limit to Sign in to control the number of Verification Emails sent per day.

2023-04-06 09:54 UTC, ThiefMaster requested changes

2023-04-06 09:54 UTC, ThiefMaster commented on indico/modules/auth/controllers.py
> +                signup_rate_limiter.hit()
```suggestion
            if signup_rate_limiter.hit():                
```

2023-04-06 09:54 UTC, ThiefMaster commented on indico/modules/auth/controllers.py
> +                flash(_('Too many verification email sent. Please wait {}').format(delay), 'warning')
```suggestion
                flash(_('Too many verification emails sent. Please wait {}').format(delay), 'warning')
```

2023-04-06 09:54 UTC, ThiefMaster commented on indico/core/config.py
> +    'SIGNUP_RATE_LIMIT': '3 per 2 minutes; 20 per day',
```suggestion
    'SIGNUP_RATE_LIMIT': '3 per 10 minutes; 20 per day',
```

should be more than enough.

also this needs to to be documented in settings.rst (like i did for `FAILED_LOGIN_RATE_LIMIT`). you can copy that text and just adapt the parts that mention logging in etc

2023-04-06 10:56 UTC, tomasr8 commented on docs/source/config/settings.rst
> +    Rate limiting is applied by IP address and each verification email sent count against the
```suggestion
    Rate limiting is applied by IP address and each verification email sent counts against the
```

2023-04-12 09:26 UTC, ThiefMaster commented on docs/source/config/settings.rst
> +    than just a few passwords).
This text doesn't really make sense here...

2023-05-02 20:45 UTC, ThiefMaster approved these changes
i refactored things a bit and also used stricter defaults

2023-05-02 20:54 UTC, merged